import { QuestionConfig } from './question-types';

export const SURVEY_QUESTIONS: QuestionConfig[] = [
  {
    id: 'q1',
    type: 'likert',
    field: 'q1OverallRating',
    commentField: 'q1Comment',
    question: 'How would you rate your overall NAM Conference experience?',
    transparency: 'This helps leadership understand overall event quality and justify future investment in conferences.',
    options: [
      { value: '5', label: '5 - Excellent' },
      { value: '4', label: '4 - Good' },
      { value: '3', label: '3 - Neutral' },
      { value: '2', label: '2 - Fair' },
      { value: '1', label: '1 - Poor' },
    ],
    commentPlaceholder: 'Additional context about your rating...',
  },
  {
    id: 'q2',
    type: 'likert',
    field: 'q2ReturnIntent',
    commentField: 'q2Comment',
    question: 'Would you want to attend NAM Conference again next year?',
    transparency: 'This helps us gauge sustained interest and plan future conference capacity.',
    options: [
      { value: '5', label: '5 - Definitely yes' },
      { value: '4', label: '4 - Probably yes' },
      { value: '3', label: '3 - Unsure' },
      { value: '2', label: '2 - Probably not' },
      { value: '1', label: '1 - Definitely not' },
    ],
    commentPlaceholder: 'Additional context about your response...',
  },
  {
    id: 'q3',
    type: 'likert-with-na',
    field: 'q3CoworkingEffectiveness',
    commentField: 'q3Comment',
    question: 'How valuable was the coworking day for networking and collaboration?',
    transparency: 'This helps us evaluate whether structured coworking time is an effective networking format for future conferences.',
    options: [
      { value: '5', label: '5 - Extremely valuable' },
      { value: '4', label: '4 - Very valuable' },
      { value: '3', label: '3 - Moderately valuable' },
      { value: '2', label: '2 - Slightly valuable' },
      { value: '1', label: '1 - Not at all valuable' },
    ],
    naLabel: 'N/A - Did not attend coworking day',
    commentPlaceholder: 'Additional context about the coworking day...',
  },
  {
    id: 'q4',
    type: 'multiple-select',
    field: 'q4ConnectionTypes',
    otherField: 'q4ConnectionOther',
    commentField: 'q4Comment',
    question: 'Who did you most value connecting with at this conference? (Select all that apply)',
    transparency: 'This helps us understand what types of connections attendees value most, so we can design networking opportunities accordingly.',
    options: [
      { value: 'leadership', label: 'EE leadership team' },
      { value: 'associates', label: 'Fellow associates in general' },
      { value: 'technical_experts', label: 'Technical experts in specific areas' },
      { value: 'similar_challenges', label: 'People working on similar challenges' },
      { value: 'different_work', label: "People I wouldn't normally interact with in day-to-day work" },
    ],
    commentPlaceholder: 'Additional context about connections you made...',
  },
  {
    id: 'q5',
    type: 'likert',
    field: 'q5ConnectionDepth',
    commentField: 'q5Comment',
    question: 'How would you describe the quality of connections you made at this conference?',
    transparency: 'This helps us understand whether the conference format supports deep connection-building versus just surface-level networking.',
    options: [
      { value: '5', label: '5 - Deep, meaningful professional relationships' },
      { value: '4', label: '4 - Strong connections with potential for follow-up' },
      { value: '3', label: '3 - Good conversations and exchanges' },
      { value: '2', label: '2 - Mostly surface-level introductions' },
      { value: '1', label: '1 - Minimal meaningful interaction' },
    ],
    commentPlaceholder: 'Additional context about connection quality...',
  },
  {
    id: 'q6',
    type: 'likert',
    field: 'q6LearningValue',
    commentField: 'q6Comment',
    question: 'How would you rate the educational/learning value of the conference content?',
    transparency: 'This helps us understand whether the conference delivers meaningful learning outcomes beyond networking.',
    options: [
      { value: '5', label: '5 - Excellent - learned significant new skills/knowledge' },
      { value: '4', label: '4 - Good - learned useful things' },
      { value: '3', label: '3 - Neutral - some learning but limited' },
      { value: '2', label: '2 - Fair - minimal learning value' },
      { value: '1', label: '1 - Poor - did not learn anything meaningful' },
    ],
    commentPlaceholder: 'Additional context about learning value...',
  },
  {
    id: 'q7',
    type: 'open-ended',
    field: 'q7FutureTopics',
    question: 'What topics would you like to see at future conferences?',
    transparency: 'This gives us ideas for future conference programming based on what you want to learn.',
    placeholder: 'Share topic ideas...',
  },
  {
    id: 'q8',
    type: 'likert-with-na',
    field: 'q8SaturdayWorth',
    commentField: 'q8Comment',
    question: 'The conference asks you to use personal time on a Saturday. Was this time commitment worth it for you?',
    transparency: "We're conscious this uses your personal Saturday time. This feedback helps leadership understand if the Saturday format is working for attendees and worth continuing.",
    options: [
      { value: '5', label: '5 - Absolutely worth it' },
      { value: '4', label: '4 - Mostly worth it' },
      { value: '3', label: '3 - Neutral' },
      { value: '2', label: '2 - Questionable value for my time' },
      { value: '1', label: '1 - Not worth my Saturday' },
    ],
    naLabel: 'N/A - Did not attend Saturday',
    commentPlaceholder: 'Additional context about the Saturday time commitment...',
  },
  {
    id: 'q9',
    type: 'likert',
    field: 'q9PreConferenceCommunication',
    commentField: 'q9Comment',
    question: 'How clear were your expectations before arriving at the conference? (Schedule, what to bring, hotel details, etc.)',
    transparency: 'This helps us improve our pre-conference communication so you know what to expect before you arrive.',
    options: [
      { value: '5', label: '5 - Very clear - knew exactly what to expect' },
      { value: '4', label: '4 - Mostly clear' },
      { value: '3', label: '3 - Somewhat clear' },
      { value: '2', label: '2 - Unclear in some areas' },
      { value: '1', label: '1 - Very unclear - arrived unsure what to expect' },
    ],
    commentPlaceholder: 'Additional context about pre-conference communication...',
  },
  {
    id: 'q10',
    type: 'likert-with-na',
    field: 'q10AccommodationsVenue',
    commentField: 'q10Comment',
    question: 'How would you rate the hotel accommodations, conference venue, and catered meals and snacks?',
    transparency: 'This helps us evaluate hotel quality, choose appropriate venues, and ensure food meets dietary needs and preferences.',
    options: [
      { value: '5', label: '5 - Excellent' },
      { value: '4', label: '4 - Good' },
      { value: '3', label: '3 - Neutral' },
      { value: '2', label: '2 - Fair' },
      { value: '1', label: '1 - Poor' },
    ],
    naLabel: 'N/A - Did not stay at conference hotel',
    commentLabel: 'Please comment if you answered Neutral or below',
    commentPlaceholder: 'Additional context about accommodations, venue, or food...',
  },
  {
    id: 'q11',
    type: 'ranking',
    field: 'q11SessionRankings',
    question: 'Rank the following session types in order of value to you (1 = most valuable, 4 = least valuable)',
    transparency: 'This helps us balance the event schedule between different session types based on what attendees value most.',
    options: [
      { value: 'presentations', label: 'Main presentations' },
      { value: 'workshops', label: 'Interactive workshops' },
      { value: 'coworking', label: 'Co-working time' },
      { value: 'networking', label: 'Networking / social time' },
    ],
  },
  {
    id: 'q12',
    type: 'single-choice',
    field: 'q12ConferenceLength',
    commentField: 'q12Comment',
    question: 'Was the overall conference length appropriate?',
    transparency: 'This helps us determine the optimal conference duration that provides value without overwhelming attendees.',
    options: [
      { value: 'too_short', label: 'Too short - wanted more time' },
      { value: 'just_right', label: 'Just right' },
      { value: 'too_long', label: 'Too long - felt too much time commitment' },
      { value: 'unsure', label: 'Unsure' },
    ],
  },
  {
    id: 'q13',
    type: 'likert-with-na',
    field: 'q13ComparisonToPD',
    commentField: 'q13Comment',
    question: "How does NAM Conference compare to other professional development opportunities you've experienced?",
    transparency: 'This helps us understand how the conference stacks up against other learning and networking opportunities available to you.',
    options: [
      { value: '5', label: '5 - Much better than other opportunities' },
      { value: '4', label: '4 - Somewhat better' },
      { value: '3', label: '3 - About the same' },
      { value: '2', label: '2 - Somewhat worse' },
      { value: '1', label: '1 - Much worse' },
    ],
    naLabel: "N/A - Haven't attended other professional development events",
    commentPlaceholder: 'Additional context about the comparison...',
  },
  {
    id: 'q14',
    type: 'open-ended',
    field: 'q14LikedMost',
    question: 'What did you like most about the conference?',
    transparency: "This helps us understand what's working well so we can preserve and enhance those elements.",
    placeholder: 'Share what you enjoyed...',
  },
  {
    id: 'q15',
    type: 'open-ended',
    field: 'q15AdditionalFeedback',
    question: "Is there anything else you'd like us to know about your conference experience?",
    transparency: "This gives you space to share anything we didn't specifically ask about.",
    placeholder: 'Share your thoughts...',
  },
  {
    id: 'q16',
    type: 'single-choice',
    field: 'q16Improvements',
    commentField: 'q16Comment',
    question: 'If you attended the last NAM Conference, did you notice improvements based on previous feedback?',
    transparency: 'This helps us understand whether attendees see their feedback being acted upon year over year.',
    options: [
      { value: 'yes_clear', label: 'Yes - clear improvements' },
      { value: 'some', label: 'Some improvements noticed' },
      { value: 'no_changes', label: 'No noticeable changes' },
      { value: 'not_sure', label: "Not sure / can't remember specific improvements" },
      { value: 'did_not_attend', label: 'Did not attend last conference' },
      { value: 'first_conference', label: 'This is my first NAM Conference' },
    ],
  },
  {
    id: 'q17',
    type: 'multiple-select',
    field: 'q17FeedbackConfidence',
    otherField: 'q17FeedbackOther',
    question: 'What would make you most confident that your feedback will be acted upon? (Select all that apply)',
    transparency: 'This helps us design a feedback loop that builds trust and shows we take your input seriously.',
    options: [
      { value: 'public_summary', label: 'Public summary of all feedback shared with attendees' },
      { value: 'action_plan', label: 'Action plan showing what will change based on feedback' },
      { value: 'visible_changes', label: "Visible changes at next conference addressing this year's issues" },
      { value: 'direct_response', label: 'Direct response acknowledging my specific feedback' },
      { value: 'explain_decisions', label: 'Conference organizers explaining decisions and trade-offs' },
      { value: 'already_confident', label: 'Nothing - I already feel confident feedback is valued' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q18',
    type: 'single-choice',
    field: 'q18EmploymentStatus',
    question: 'What is your current status with Equal Experts?',
    transparency: 'This helps us understand experience differences between employees and associates.',
    options: [
      { value: 'employee', label: 'Employee' },
      { value: 'active_associate', label: 'Active Associate' },
      { value: 'alumni_associate', label: 'Alumni Associate' },
      { value: 'client', label: 'Client' },
      { value: 'prefer_not', label: 'Prefer not to answer' },
    ],
  },
  {
    id: 'q19',
    type: 'text-field',
    question: 'If comfortable please provide your name and home city and state. (This helps us follow up on specific feedback if needed)',
    transparency: 'Providing your name and home location is completely optional. Anonymous responses are equally valuable.',
    fields: [
      {
        id: 'name',
        label: 'Your Name',
        field: 'q19Name',
        placeholder: 'Leave blank to remain anonymous',
      },
      {
        id: 'location',
        label: 'City and State',
        field: 'q19Location',
        placeholder: 'Leave blank to remain anonymous',
      },
    ],
  },
];

export const TOTAL_QUESTIONS = SURVEY_QUESTIONS.length;
